[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24"

# Redirects for SPA and API proxy
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://qqveojewxoexrwuxrjsk.supabase.co/functions/v1/:splat"
  status = 200
  force = true

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self' data:;
      connect-src 'self' https://qqveojewxoexrwuxrjsk.supabase.co wss://qqveojewxoexrwuxrjsk.supabase.co https://mainnet.infura.io https://api.coingecko.com;
      frame-src 'none';
    """

# Cache static assets (JS, CSS, fonts)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Prevent caching of HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Context-specific build configurations
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"
